title: Mudasser Shaik # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  - ğŸ‘‹ Hi, Iâ€™m @mudassershaik
  - ğŸ‘€ Iâ€™m interested in combining the powers of BigData, Information Quality and AI.
  - ğŸŒ± Iâ€™m currently learning probabilistic programing and GCP.
  - âœ¨ I specialize in Apache Spark, Apache Beam, Hadoop and Kafka EcoSystem - Kafka-Connect-KStreams-kSQL.
  - ğŸ’ï¸ Iâ€™m looking to collaborate on Streaming Systems, Data Initatives, ML-Ops.
  - ğŸ“« How to reach me - Slack `@Mudasser Shaik`
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/mudasser-shaik/"> LinkedIn Profile</a>
  <!-- Social Icons -->
  <ul class="icons">
  	<li><a href="https://twitter.com/mudasser_smd" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
  	<li><a href="https://www.linkedin.com/in/mudasser-shaik/" class="icon brands fa-linkedin"><span class="label">LinkedIn</span></a></li>
  	<li><a href="https://github.com/mudasser-shaik" class="icon brands fa-github"><span class="label">Github</span></a></li>
  	<li><a href="" class="icon brands fa-medium"><span class="label">Medium</span></a></li>
  </ul>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
