title: Mudasser Shaik # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  - ğŸ‘‹ Hi, Iâ€™m @mudassershaik
  - ğŸ‘€ Iâ€™m interested in combining the powers of BigData, Information Quality and AI.
  - ğŸŒ± Iâ€™m currently learning probabilistic programing and GCP.
  - âœ¨ I specialize in Apache Spark, Apache Beam, Hadoop and Kafka EcoSystem - Kafka-Connect-KStreams-kSQL.
  - ğŸ’ï¸ Iâ€™m looking to collaborate on Streaming Systems, Data Initatives, ML-Ops.
  - ğŸ“« How to reach me - Slack `@Mudasser Shaik`
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/mudasser-shaik/"> LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
